### ISSUE TITLE
logo not following design standards and print specifications

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_artwork#1]
We are trying to get the logo printed and we receive a number of requests from the printing company to fix the logo in this folder: https://github.com/loklak/loklak_artwork/tree/master/svg

The complete requirements are in English here: https://www.flyeralarm.com/uk/content/index/open/id/1569/artwork-requirements.html

These are the issues we receive in German:
* Fehler: Datenformat nicht korrekt
Das Datenformat Ihrer Druckdaten weicht von dem benötigten Datenformat ab.
* Hinweis: Transparenzen werden verwendet
Ihre Daten enthalten Transparenzen. Diese können beim Belichten Probleme verursachen und zu unerwünschten Druckergebnissen führen. Bitte entfernen Sie die Transparenzen aus Ihren Daten.
* Hinweis: Auflösung zu gering
Die Auflösung der von Ihnen gesendeten Druckdaten ist zu gering. Bitte passen Sie die Auflösung Ihrer Daten entsprechend den Angaben auf unserer Website (mindestens 300 dpi, optimale Auflösung 356 dpi/140 ppcm) an. Beachten Sie, dass für bestimmte Produkte andere Mindestauflösungen gelten. Weitere Informationen finden Sie unter dem Punkt "Druckdaten".
* Hinweis: Farbraum ist nicht CMYK
Ihre Druckdaten enthalten entweder RGB- oder Lab-Farbräume. Für den Druck Ihres Auftrages benötigen wir jedoch Daten im CMYK-Farbraum. Damit es beim Druck nicht zu Farbabweichungen/Fehlinterpretationen kommt, bitten wir Sie, Ihre Daten zu korrigieren.

The goal is to get a professional printable image in pdf or svg as below.
![loklak_sticker_yellow](https://user-images.githubusercontent.com/1583873/35364028-5188f384-016d-11e8-8353-aca0b410c0b4.jpg)

**Comment by elioqoshi** [comment]
[LokLakSticker.pdf](https://github.com/loklak/loklak_artwork/files/1663470/LokLakSticker.pdf)

This should work.

**Comment by elioqoshi** [comment]
[LokLakSticker.pdf](https://github.com/loklak/loklak_artwork/files/1663498/LokLakSticker.pdf)
.org

**Comment by fabiyamada** [comment]
Hello!
I know you  were asking to get the vector file of your current logo but I couldn't resist to offer you a redesign.

![loklak logo sample](https://user-images.githubusercontent.com/33674731/36881724-e325d7ea-1d8c-11e8-97bd-72398f9476d7.png)

You can read more about it here: https://steemit.com/utopian-io/@fabiyamada/logo-design-for-loklak
And find all the files here: https://github.com/fabiyamada/logos/tree/master/loklak

I hope to hear what you think about it :) 
Greetings!
